name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - python
  - matplotlib=3.2.2
  - pandas=1.0.4
  - bqplot=0.12.30
  - geopandas
  - ipywidgets
  - contextily
  - openpyxl
  - seaborn
  - IPython
