name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - python
  - pip:
    - matplotlib
    - pandas
    - bqplot
    - geopandas
    - ipywidgets
    - contextily
    - openpyxl
